config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: 'landing#index'
  post :like, to: 'votes#like'

  resources :users, only: [:show]
  resources :tweets, only: [:create, :index]
  resources :followers, only: [:create, :destroy]
  resources :notifications, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :votes
  belongs_to :user

  validates :body, length: { maximum: 240 }, presence: true

  def total_likes
    votes.where(like: 1).count
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :followers
  has_many :followings
  has_many :votes
  has_many :notifications

  def total_followers
    followers.all.count
  end

  def total_followings
    followings.all.count
  end

  def total_new_notifications
    notifications.where(read: 0).count
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find_by(id: params[:user_id])
    @follower = @user.followers.build(follower_id: current_user.id)

    @following = current_user.followings.build(following_id: @user.id)

    @notification = @user.notifications.build(body: "#{current_user.username} has followed you!")

    if @follower.save && @following.save && @notification.save
      flash[:success] = "You've followed #{@user.username}"
      redirect_to(:back)
    end
  end

  def destroy
    @user = User.find_by(id: params[:user_id])
    @follower = @user.followers.find_by(follower_id: current_user.id)

    @following = current_user.followings.find_by(following_id: @user.id)

    if @follower.destroy && @following.destroy
      flash[:success] = "You've unfollowed #{@user.username}"
      redirect_to(:back)
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    if current_user
      following = current_user&.followings&.all
      following_id = [current_user.id]

      following&.each do |following|
        following_id << following.following_id
      end

      @tweets = Tweet.where(user_id: following_id).order(created_at: :desc)
      @tweet = Tweet.new
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  after_action :read_notification

  def index
    @notifications = current_user.notifications.all.order(created_at: :desc)
  end

  private

  def read_notification
    @notifications.each do |notification|
      notification.update(read: 1)
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @tweets = Tweet.where("created_at >= ?", Time.zone.now.beginning_of_day)
    @popular = []

    if @tweets.count < 10
      number_of_tweets = @tweets.count
    else
      number_of_tweets = 10
    end

    for i in 1..number_of_tweets
      most_like_tweet = Tweet.new
      @tweets.each do |tweet|
        if tweet.total_likes >= most_like_tweet.total_likes
          most_like_tweet = tweet
        end
      end
      @popular << most_like_tweet
      @tweets = @tweets.without(most_like_tweet)
    end
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    @followers = current_user.followers.all

    if @tweet.save
      flash[:success] = "You've tweeted!"

      @followers.each do |follower|
        @follower = User.find_by(id: follower.follower_id)
        @notification = @follower.notifications.build(body: "#{current_user.username} has a new tweet!")
        @notification.save
      end
      
      redirect_to(:back)
    else
      flash[:danger] = @tweet.errors.full_messages
      redirect_to(:back)
    end
  end

  private

    def tweet_params
      params.require(:tweet).permit(:body)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
    @tweets = Tweet.where(user_id: params[:id]).order(created_at: :desc)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_or_create_vote

  def like
    if @vote.like == 1
      value = 0
    else
      value = 1
    end

    update_vote(value)
  end

  private

  def find_or_create_vote
    @vote = current_user.votes.find_or_create_by(tweet_id: params[:tweet_id])
  end

  def update_vote(value)
    if @vote
      @vote.update(like: value)
      redirect_to(:back)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_messages_helper.rb
module FlashMessagesHelper

  def display_message(value)

    return content_tag(:p, value) unless value.kind_of?(Array)

    content_tag :ul do
      value.collect { |message| content_tag(:li, message, class: 'list-styling') }.join.html_safe
    end
  end
end

app/views/landing/index.html.erb
<div class="dashboard-container">
  <% if current_user %>
    <div class="profile">
      <%= render partial: "partials/profile", locals: { user: current_user } %>
    </div>
    <div class="tweet">
      <%= form_for(@tweet, url: tweets_path, method: :post, html: { id: "tweet-create-form", multipart: true }) do |f| %>
        <div class="form-group">
          <h4> <%= f.label :text_field, "New Tweet:" %> </h4>
          <%= f.text_field :body, id: "tweet_body_field", class: 'form-control' %>
        </div>

        <div class="form-group text-center">
          <%= f.submit "Tweet!", class: "btn btn-success btn-lg" %>
        </div>
      <% end %>

      <h3>Timeline</h3>
      <%= render partial: "partials/tweets", locals: { tweets: @tweets } %>
    </div>
  <% else %>
    <div class="text-container">
      <h1>Please register or login to enjoy the TwitterApp!</h1>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <%= render partial: 'partials/header' %>
    </div>
    <%= render partial: "partials/flash_messages" %>
    <%= yield %>
  </body>
</html>

app/views/notifications/index.html.erb
<div class="notifications">
  <% if @notifications.empty? %>
    <h3 class="text-center">No notifications</h3>
  <% else %>
    <% @notifications.each do |notification| %>
      <div class="notification-container">
        <% if notification.read == 0 %>
          <h6 class="text-center">New</h6>
        <% end %>
        <h4 class="text-center"><%= notification.body %></h4>
      </div>
    <% end %>
  <% end %>
</div>

app/views/partials/_flash_messages.html.erb
<div id="flash-messages-container">
  <% flash.each do |k,v| %>
    <section class="flash-messages">
      <div class="alert alert-<%=k%>">
        <button type="button" class="close" data-dismiss="alert">
          &times;
        </button>
        <div class="message">
          <%= display_message(v) %>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "TwitterApp", root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-dropdown" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="header-dropdown">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Popular Tweets!", tweets_path, class: 'white shadowed link-styling' %></li>
        <% if current_user %>
          <li><%= link_to "#{current_user.username}", user_path(current_user), class: 'white shadowed link-styling' %></li>
          <li><%= link_to "#{current_user.total_new_notifications} notifications", notifications_path, class: 'white shadowed link-styling' %></li>
          <li><%= link_to "Log-out", destroy_user_session_path, method: :Delete, class: 'white shadowed link-styling' %></li>
        <% else %>
          <li><%= link_to "Register", new_user_registration_path %></li>
          <li><%= link_to "Log-in", new_user_session_path %></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_profile.html.erb
<div class="profile-container">
  <h1 class="text-center"><%= user.username %></h1>
  <h5 class="text-center"><%= user.name %></h5>

  <% if current_user&.id != user.id %>
    <% if current_user&.followings&.find_by(following_id: user.id) %>
      <%= link_to "Followed", follower_path(user_id: user.id), method: :delete, data: { confirm: "Unfollow?"}, class: "btn btn-info btn-block" %>
    <% else %>
      <%= link_to "Follow", followers_path(user_id: user.id), method: :post, class: "btn btn-primary btn-block" %>
    <% end %>
  <% end %>

  <div class="details-container">
    <div class="follower-container">
      <h3><%= user.total_followers %></h3>
      <h5>Followers<h5>
    </div>
    <div class="follower-container">
      <h3><%= user.total_followings %></h3>
      <h5>Following<h5>
    </div>
  </div>
</div>

app/views/partials/_tweets.html.erb
<% tweets.each do |tweet| %>
  <div class="tweet-container">
    <div class="text-container">
      <%= link_to "#{tweet.user.username}", user_path(tweet.user), class: 'white shadowed link-styling' %>
      <div class="body-container">
        <h3><%= tweet.body %></h3>
      </div>
      <h6>Tweeted at <%= tweet.created_at.strftime("%I:%M %p %e/%m") %></h6>
    </div>

    <div class="like-container">
      <%= link_to like_path(tweet_id: tweet.id), method: :post, class: "btn btn-block", id: "like-button" do %>
        <% if current_user&.votes&.find_by(tweet_id: tweet.id)&.like == 1 %>
          <i class="fa fa-heart" aria-hidden="true"></i>
        <% else %>
          <i class="fa fa-heart-o" aria-hidden="true"></i>
        <% end %>
        <h5 class="likes-description"><%= tweet.total_likes %></h5>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tweets/index.html.erb
<div class="dashboard-container">
    <div class="profile">
      <h1 class="text-center">Most Popular Tweets For The Day!</h1>
    </div>
    <div class="tweet">
      <% if @popular.empty? %>
        <h3 class="text-center">There are currently no new tweet for today yet.</h3>
      <% else %>
        <%= render partial: "partials/tweets", locals: { tweets: @popular } %>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="dashboard-container">
  <div class="profile">
    <%= render partial: "partials/profile", locals: { user: @user } %>
  </div>
  <div class="tweet">
    <h3>Tweets</h3>
    <%= render partial: "partials/tweets", locals: { tweets: @tweets } %>
  </div>
</div>